[project]
name = "torchfx"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Matteo Spanio", email = "spanio@dei.unipd.it" }
]
requires-python = ">=3.10"
dependencies = [
    "annotated-types>=0.7.0",
    "numpy>=2.2.4",
    "scipy>=1.15.2",
    "torch>=2.6.0",
    "torchaudio>=2.6.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
