name: Test and lint

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint-test:
    name: Lint, Type Check, and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: |
          pip install uv

      - name: Install dependencies
        run: |
          uv pip install .[cli,dev]

      - name: Check formatting with Black
        run: |
          black --check src tests

      - name: Lint with Ruff
        run: |
          ruff check src tests
          ruff format --check src tests

      - name: Type check with mypy
        run: |
          mypy src

      - name: Run tests with pytest
        run: |
          pytest
